function Keit2000MeasureChoose( src, ~ ,data_object,gui_object)
    % changes interface according to measure choice
    
    % get structs from objects
    data=guidata(data_object);
    gui=guidata(gui_object);
    
    v=get(src,'value');
    set(gui.MeasureRangePopup,'Value',1);
    if v==2
        set(gui.MeasureRangePopup,'string',{'1000 V',...
            '100 V',...
            '10 V',...
            '1 V',...
            '100 mV'});
    elseif v==1
        set(gui.MeasureRangePopup,'string',{'3 A',...
            '1 A',...
            '100 mA',...
            '10 mA'});
    end
end