function Keit2400SourceChoose( src, ~ ,data_object,gui_object)
    % changes interface according to source choice
    
    % get structs from objects
    data=guidata(data_object);
    gui=guidata(gui_object);
    
    v=get(src,'value');
    set(gui.MeasureRangePopup,'Value',1);
    set(gui.SourceRangePopup,'Value',1);
    if v==1
        set(gui.SourceRangePopup,'string',{'210 V',...
            '21 V',...
            '2.1 V',...
            '210 mV'});
    set(gui.MeasureCompUnitPopup,'string',{'A',...
            'mA','µA'});
    set(gui.MeasureRangePopup,'string',{'1.05 A',...
            '105 mA',...
            '10.5 mA',...
            '1.05 mA',...
            '105 µA',...
            '10.5 µA',...
            '1.05 µA'});
    elseif v==2
        set(gui.SourceRangePopup,'string',{'1.05 A',...
            '105 mA',...
            '10.5 mA',...
            '1.05 mA',...
            '105 µA',...
            '10.5 µA',...
            '1.05 µA'});
        set(gui.MeasureCompUnitPopup,'string',{'V',...
            'mV','µV'});
        set(gui.MeasureRangePopup,'string',{'210 V',...
            '21 V',...
            '2.1 V',...
            '210 mV'});
    end
end