function gui = CreateInterface(data_object)
    % Create the user interface for the application and return a
    % structure of handles for global use.
    
    % get struct from object
    data=guidata(data_object);
    
    %create list of command examples
    examplelist = {'set keithley1.dcv num',...
        'set keithley1.dcc num',...
        'set keithley1 returntozero on/off',...
        'set keithley2.dcv num',...
        'set keithley2.dcc num',...
        'set keithley2 returntozero on/off',...
        'set lockin1.acv num',...
        'set lockin1.freq num',...
        'set lockin1.auxdcv1 num',...
        'sweep keithley2.dcv 0 1 5',...
        'sweep keithley1.dcv 0 1 5 keithley2.dcv 0 1 5 ',...
        'move keithley1.dcv 0 1 10',...
        'set magnet.field zero',...
        'set magnet.field on num',...
        'record num'};

    gui = struct();
    %% Open a window and add menus
    gui.Window = figure( ...
        'Name', 'Measuring Menu', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'Toolbar', 'none', ...
        'Position', [500,50,500,950], ...
        'HandleVisibility', 'off');

    % File menu
    gui.FileMenu = uimenu( gui.Window, 'Label', 'File' );

    % Help menu
    helpMenu = uimenu( gui.Window, 'Label', 'Help' );
    uimenu( helpMenu, 'Label', 'Documentation', 'Callback', @Prog_Help );

    % Arrange the main interface
    mainLayout = uiextras.VBox( 'Parent', gui.Window, 'Spacing', 5 );

    % Create the panels
    controlPanel = uiextras.BoxPanel( ...
        'Parent', mainLayout);

    tabPanel = uiextras.TabPanel( ...
        'Parent', mainLayout );

    commandPanel = uiextras.BoxPanel( ...
        'Parent', mainLayout );

    gui.ViewPanel = uiextras.BoxPanel( ...
        'Parent', mainLayout, ...
        'Title', 'Plots');

    % Adjust the main layout
    set( mainLayout, 'Sizes', [-1,-2,-3,-7]  );

    %% Create the controls
    
    %controlPanel
    controlLayout = uiextras.HBox( 'Parent', controlPanel, ...
        'Padding', 3, 'Spacing', 3 );
    gui.ShowInstrumentsButton = uicontrol( 'Style', 'PushButton', ...
        'BackgroundColor', [0.941,0.941,0.941], ...
        'Parent', controlLayout, ...
        'String', 'Set Instruments');
    gui.RefreshButton=uicontrol( 'Style', 'PushButton', ...
        'BackgroundColor', 'r', ...
        'Parent', controlLayout, ...
        'String', 'REFRESH');
    set( controlLayout, 'Sizes', [-3 -1] ); % Make the list fill the space

    %tabPanel
    
    %measuretab
    measureTabLayout = uiextras.VBox( 'Parent', tabPanel, ...
        'Padding',10 , 'Spacing', 3 );
    gui.TextMeasure = uicontrol( 'Style', 'text', ...
        'Parent', measureTabLayout, ...
        'String', 'Measure:',...
        'Fontsize', 15);
    
    % load previous measurement measured properties
    mn=load(fullfile(data.sourcepath,'lastmeasured.mat'));
    data.MeasuredNames=strtrim(strsplit(mn.measname,','));
    gui.EditMeasure = uicontrol( 'Style', 'edit', ...
        'BackgroundColor', 'w', ...
        'Fontsize', 15,...
        'Max', 100,...
        'Parent', measureTabLayout, ...
        'String', mn.measname);

    %%%%%%%%%%%%horizontal bar%%%%%%%%%%%%%%%%%%
    % must recognizae findjobj.m to work
    %# enable horizontal scrolling
    jEdit = findjobj(gui.EditMeasure);
    jEditbox = jEdit.getViewport().getComponent(0);
    jEditbox.setWrapping(false);                %# turn off word-wrapping
    set(jEdit,'HorizontalScrollBarPolicy',30);  %# HORIZONTAL_SCROLLBAR_AS_NEEDED

    %# maintain horizontal scrollbar policy which reverts back on component resize 
    hjEdit = handle(jEdit,'CallbackProperties');
    set(hjEdit, 'ComponentResizedCallback',...
        'set(gcbo,''HorizontalScrollBarPolicy'',30)')
    set( measureTabLayout, 'Sizes', [-1 -4] ); % Make the list fill the space
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    %sweeptab
    sweepTabLayout = uiextras.VBox( 'Parent', tabPanel, ...
        'Padding', 3, 'Spacing', 3 );
    TimeStepLayout = uiextras.HBox( 'Parent', sweepTabLayout, ...
        'Padding', 3, 'Spacing', 3 );
    gui.TextTimeStep=uicontrol( 'Style', 'text', ...
        'String', 'Time Step:', ...
        'Parent', TimeStepLayout );
    gui.EditTimeStep=uicontrol( 'Style', 'edit', ...
        'String', '1', ...
        'BackgroundColor', 'w', ...
        'Parent', TimeStepLayout);
    DoubleTimeStepLayout = uiextras.HBox( 'Parent', sweepTabLayout, ...
        'Padding', 3, 'Spacing', 3 );
    gui.TextDoubleTimeStep=uicontrol( 'Style', 'text', ...
        'String', 'Double Time Step:', ...
        'Parent', DoubleTimeStepLayout );
    gui.EditDoubleTimeStep=uicontrol( 'Style', 'edit', ...
        'String', '1', ...
        'BackgroundColor', 'w', ...
        'Parent', DoubleTimeStepLayout);
    DoubleSweepLayout = uiextras.HBox( 'Parent', sweepTabLayout, ...
        'Padding', 3, 'Spacing', 3 );
    gui.TextDoubleSweepMode=uicontrol( 'Style', 'text', ...
        'String', 'Double Sweep mode:', ...
        'Parent', DoubleSweepLayout );
    gui.ListDoubleSweepMode = uicontrol( 'Style', 'popup', ...
        'BackgroundColor', 'w', ...
        'Parent', DoubleSweepLayout, ...
        'String', {'Normal','there and back','sulamot'});

    %filetab
    FileCommentTabLayout = uiextras.VBox( 'Parent', tabPanel, ...
        'Padding', 3, 'Spacing', 3 );
    FileTabLayout = uiextras.HBox( 'Parent', FileCommentTabLayout, ...
        'Padding', 3, 'Spacing', 3 );
    gui.ChooseFolder = uicontrol( 'Style', 'PushButton', ...
        'Parent', FileTabLayout, ...
        'String', 'Choose folder');
    FileEditlayout = uiextras.VBox( 'Parent', FileTabLayout, ...
        'Padding', 3, 'Spacing', 3 );
    gui.EditChooseFolder = uicontrol( 'Style', 'edit', ...
        'BackgroundColor', 'w', ...
        'Parent', FileEditlayout, ...
        'Enable', 'Inactive', ...
        'String', 'directory');
    gui.EditComponent = uicontrol( 'Style', 'edit', ...
        'BackgroundColor', 'w', ...
        'Parent', FileEditlayout, ...
        'String', 'component name');        
    CommentTabLayout = uiextras.HBox( 'Parent', FileCommentTabLayout, ...
        'Padding', 3, 'Spacing', 3 );
    gui.AddComment = uicontrol( 'Style', 'PushButton', ...
        'Parent', CommentTabLayout, ...
        'String', 'add comment to last file', ...
        'Enable', 'off');
    gui.EditComment = uicontrol( 'Style', 'edit', ...
        'BackgroundColor', 'w', ...
        'Max',100,...
        'Parent', CommentTabLayout, ...
        'String', 'comment');

    tabPanel.TabNames = {'Measure', 'Sweep', 'File'};
    tabPanel.SelectedChild=1;

    %CommandPanel
    commandLayout = uiextras.VBox( 'Parent', commandPanel, ...
        'Padding', 3, 'Spacing', 3 );
    gui.ListCommand = uicontrol( 'Style', 'popup', ...
        'BackgroundColor', 'w', ...
        'Parent', commandLayout, ...
        'String', examplelist);
    gui.EditCommand = uicontrol( 'Style', 'edit', ...
        'BackgroundColor', 'w', ...
        'Parent', commandLayout, ...
        'String', 'command');
    FileNameLayout = uiextras.HBox( 'Parent', commandLayout, ...
        'Padding', 3, 'Spacing', 3 );
    gui.TextFileName1=uicontrol( 'Style', 'text', ...
        'BackgroundColor', [0.941,0.941,0.941], ...
        'Fontsize', 10,...
        'String', 'will save to: ', ...
        'Parent', FileNameLayout );
    gui.TextFileName2=uicontrol( 'Style', 'edit', ...
        'BackgroundColor', 'w', ...
        'String', 'comp-1', ...
        'Enable', 'Inactive',...
        'Max', 100,...
        'Parent', FileNameLayout );
    gui.CheckContinue=uicontrol( 'Style', 'checkbox', ...
        'String', 'continue last measurement', ...
        'Parent', FileNameLayout,...
        'Enable', 'off');
    goBoxLayout = uiextras.HBox( 'Parent', commandLayout, ...
        'Padding', 3, 'Spacing', 3 );
    gui.GoButton=uicontrol( 'Style', 'PushButton', ...
        'Parent', goBoxLayout, ...
        'String', 'go');
    gui.StopButton=uicontrol( 'Style', 'PushButton', ...
        'Parent', goBoxLayout, ...
        'String', 'Stop');
    set( commandLayout, 'Sizes', [-1 -1 -1 -2] );

    % Create the view
    ViewLayout = uiextras.VBox( 'Parent', gui.ViewPanel, ...
        'Padding', 3, 'Spacing', 3, 'Visible', 'on' );
    AddLivePlotLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
    gui.AddLivePlotButton=uicontrol( 'Style', 'PushButton', ...
        'Parent', AddLivePlotLayout, ...
        'String', 'add live plot');
    AxisChoicetextLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
    uicontrol( 'Style', 'text', ...
        'String', 'X axis:', ...
        'Parent', AxisChoicetextLayout );
    uicontrol( 'Style', 'text', ...
        'String', 'Y axis:', ...
        'Parent', AxisChoicetextLayout );
    AxisChoiceLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
    gui.ListChooseX1 = uicontrol( 'Style', 'popup', ...
        'BackgroundColor', 'w', ...
        'Parent', AxisChoiceLayout, ...
        'String', ' ');
    gui.ListChooseY1 = uicontrol( 'Style', 'popup', ...
        'BackgroundColor', 'w', ...
        'Parent', AxisChoiceLayout, ...
        'String', ' ');
    gui.ViewAxes1 = axes( 'Parent', ViewLayout );

    % creating menu for matlab plot editting
    gui.graphmenu = uicontextmenu('Parent',gui.Window);
    set(gui.ViewAxes1,'uicontextmenu',gui.graphmenu);

    set( ViewLayout, 'Sizes', [-1 -1 -2 -10] );
    
    % update data object
    guidata(data_object,data);
end