function LoadMeasurementMenu( ~,~,data_object,gui_object)
    % creates gui for loading measurements

    % get structs from objects
    data=guidata(data_object);
    gui=guidata(gui_object);
    
    % initialize strings
    filestr='';
    dataversion='';
    date='';
    comments='';
    sizes='none';


    % create the window
    LodingMenuWindow = figure( ...
        'Name', 'Loading Menu', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'Toolbar', 'none', ...
        'Position', [530 100 660 810], ...
        'HandleVisibility', 'off' );
    
    % add buttons
    ViewLayout = uiextras.VBox( 'Parent', LodingMenuWindow, ...
        'Padding', 3, 'Spacing', 3, 'Visible', 'on' );
    LoadLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
    uicontrol( 'Style', 'PushButton', ...
        'String', 'open file', ...
        'Parent', LoadLayout,...
        'Callback', {@LoadMeasurement,data_object,gui_object});
    FileNameLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
    uicontrol( 'Style', 'text', ...
        'String', 'file name:', ...
        'Parent', FileNameLayout );
    gui.LoadFileText=uicontrol( 'Style', 'text', ...
        'Background', 'white',...
        'String', filestr, ...
        'Parent', FileNameLayout );
    DataVersionLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
    uicontrol( 'Style', 'text', ...
        'String', 'data version:', ...
        'Parent', DataVersionLayout );
    gui.LoadDataVersion=uicontrol( 'Style', 'text', ...
        'Background', 'white',...
        'String', dataversion, ...
        'Parent', DataVersionLayout );
    DateLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
    uicontrol( 'Style', 'text', ...
        'String', 'date:', ...
        'Parent', DateLayout );
    gui.LoadDate=uicontrol( 'Style', 'text', ...
        'Background', 'white',...
        'String', date, ...
        'Parent', DateLayout );
    CommentsLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
    uicontrol( 'Style', 'text', ...
        'String', 'comments:', ...
        'Parent', CommentsLayout );
    gui.LoadComments=uicontrol( 'Style', 'edit', ...
        'Enable', 'on',...
        'Max', 100,...
        'Background', 'white',...
        'String', comments, ...
        'Parent', CommentsLayout );

    % create view
    AxisChoicetextLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
    uicontrol( 'Style', 'text', ...
        'String', 'X axis:', ...
        'Parent', AxisChoicetextLayout );
    uicontrol( 'Style', 'text', ...
        'String', 'Y axis:', ...
        'Parent', AxisChoicetextLayout );
    AxisChoiceLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
    gui.LoadListChooseX = uicontrol( 'Style', 'popup', ...
        'BackgroundColor', 'w', ...
        'Parent', AxisChoiceLayout, ...
        'String', sizes);
    gui.LoadListChooseY = uicontrol( 'Style', 'popup', ...
        'BackgroundColor', 'w', ...
        'Parent', AxisChoiceLayout, ...
        'String', sizes);
    
    % create joint plot buttons
    JointListLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
    JointOpen=uicontrol( 'Style', 'PushButton', ...
        'String', 'open joint figure', ...
        'Parent', JointListLayout);
    gui.JointIndex=1;
    gui.LoadJointTable = uitable('columnname', {'Yes/No'},...
                     'columnformat',{'logical'},...
                     'ColumnEditable', true,...
                     'rowname','none',...
                     'data',false,...
                     'Parent', JointListLayout);
    gui.LoadViewAxes = axes( 'Parent', ViewLayout );

    % create menu for matlab plot editting
    graphmenu = uicontextmenu('Parent',LodingMenuWindow);
    uimenu(graphmenu,'Label','open in figure','Callback',{@LoadOpenFigure,gui});
    
    % create menu for joint plot
    uimenu(graphmenu,'Label','add to joint plot','Callback',{@LoadAddToJoint,data_object,gui_object});
    set(gui.LoadViewAxes,'uicontextmenu',graphmenu);
    
    % set callbacks
    set(JointOpen,'Callback', {@LoadOpenJointFigure,data_object,gui_object});
    set(gui.LoadListChooseY,'Callback', {@LoadUpdateGraph,data_object,gui_object});
    set(gui.LoadListChooseX,'Callback', {@LoadUpdateGraph,data_object,gui_object});
    
    % arrange view
    set( ViewLayout, 'Sizes', [-1 -1 -1 -1 -2 -1 -1 -5 -10] );
    
    % update data and gui obpjects
    guidata(data_object,data);
    guidata(gui_object,gui);
end