function AddLivePlot(~,~,data_object,gui_object)
    % opens new figure with live plot

    % get structs from objects
    data=guidata(data_object);
    gui=guidata(gui_object);
    
    % add plot number to list of active figures
    NewPlotNum=data.liveplots(end)+1;
    
    % open figure and buttons
    Window = figure( ...
        'Name', 'Measuring Menu', ...
        'Position', [1000,50,450,450],...
        'UserData', NewPlotNum,...
        'CloseRequestFcn',{@LiveCloseReq,data_object});
    ViewLayout = uiextras.VBox( 'Parent', Window, ...
        'Padding', 3, 'Spacing', 3, 'Visible', 'on' );
    AxisChoicetextLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
    uicontrol( 'Style', 'text', ...
        'String', 'X axis:', ...
        'Parent', AxisChoicetextLayout );
    uicontrol( 'Style', 'text', ...
        'String', 'Y axis:', ...
        'Parent', AxisChoicetextLayout );
    AxisChoiceLayout = uiextras.HBox( 'Parent', ViewLayout, ...
        'Padding', 3, 'Spacing', 3 );
   sizes=[data.SweepedNames,data.MeasuredNames]; 
   gui.(['ListChooseX',num2str(NewPlotNum)]) = uicontrol( 'Style', 'popup', ...
        'BackgroundColor', 'w', ...
        'Parent', AxisChoiceLayout, ...
        'String', sizes, ...
        'Callback', {@XAxisChange,data_object,gui_object});
    gui.(['ListChooseY',num2str(NewPlotNum)]) = uicontrol( 'Style', 'popup', ...
        'BackgroundColor', 'w', ...
        'Parent', AxisChoiceLayout, ...
        'String', sizes, ...
        'Callback', {@YAxisChange,data_object,gui_object});
    gui.(['ViewAxes',num2str(NewPlotNum)]) = axes( 'Parent', ViewLayout );
    set( ViewLayout, 'Sizes', [-1 -1 -10] );
    
    % update list of open figures
    data.liveplots=[data.liveplots,NewPlotNum];
    
    % update data and gui objects
    guidata(data_object,data);
    guidata(gui_object,gui);
end